<a href="https://colab.research.google.com/github/KorwinBieniek/NumPyExercises/blob/main/NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

## Importing NumPy and printing version number

In [ ]:
import numpy as np

print(np.__version__)

1.21.5


## EXERCISE 1 - Element-wise addition of 2 numpy arrays
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 3, 5], [0, 2, 4]])

sum_arr = arr1 + arr2
sum_arr

array([[ 2,  5,  8],
       [ 4,  7, 10]])

## EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar
Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [ ]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
scalar = 5

arr * scalar

array([[ 5, 10, 15],
       [ 5, 10, 15]])

## EXERCISE 3 - Identity Matrix
Create an identity matrix of dimension 4-by-4

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## EXERCISE 4 - Array re-dimensioning
Convert a 1-D array to a 3-D array

In [ ]:
arr1d = np.array([x for x in range(27)])

arr3d = arr1d.reshape(3, 3, 3)

arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## EXERCISE 5 - Array datatype conversion
Convert all the elements of a numpy array from float to integer datatype

In [ ]:
arr_floats = np.array([1.2, 3.5, 4.6, 2.2, -1.3, 0.0, 3, 3.6, 7.8, 11.2])

arr_ints = arr_floats.astype('int')

arr_ints

array([ 1,  3,  4,  2, -1,  0,  3,  3,  7, 11])

## EXERCISE 6 - Obtaining Boolean Array from Binary Array
Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [ ]:
bin_arr = np.array([[1, 0, 1], [1, 1, 1], [0, 0, 0]])

bool_arr = bin_arr.astype('bool')

bool_arr

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

## EXERCISE 7 - Horizontal Stacking of Numpy Arrays
Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 4, 5, 6])

h_stacked_arr = np.hstack((arr1, arr2))

h_stacked_arr

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

## EXERCISE 8 - Vertically Stacking of Numpy Arrays
Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 4, 5, 6])

v_stacked_arr = np.vstack((arr1, arr2))

v_stacked_arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

## EXERCISE 9 - Custom Sequence Generation
Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [ ]:
rand_arr = np.array([x for x in range(0, 101, 2)])

rand_arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## EXERCISE 10 - Getting the positions (indexes) where elements of 2 numpy arrays match
From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 3, 3, 2, 5])

print(np.where(arr1 == arr2))

(array([0, 2, 4]),)


## EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range
Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

## EXERCISE 12 - Matrix Generation with one particular value
Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

## EXERCISE 13 - Array Generation by repeatition of a small array across each dimension
Output an array by repeating a smaller array of 2 dimensions, 10 times

## EXERCISE 14 - Array Generation of random integers within a specified range
Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

## EXERCISE 15 - Array Generation of random numbers following normal distribution
Output a 3-by-3 array of random numbers following normal distribution

## EXERCISE 16 - Matrix Multiplication
Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

## EXERCISE 17 - Matrix Transpose
Output the transpose of a matrix (as numpy array)

## EXERCISE 18 - Sine of an Angle (in radians)
Calculate the sine of an array of angles (in radians) using NumPy

## EXERCISE 19 - Cosine Similarity
Calculate the cosine similarity of 2 vectors (as numpy arrays)

## EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order
Output the array element indexes such that the array elements appear in the ascending order